#define INSTRUMENT_VERSION "1.0"
#define INSTRUMENT_ID "001"
#define HELLO_MSG "ATXBOOT"

/* Sygna³y wyjsciowe */
#define ZP 1
#define SA 0

/* Sygna³y wejsciowe */
#define KA 2
#define F 3
#define SW 4
#define PRZERWA 5

/* Funkcje */
#define FUNCTION_BASE 0x41
#define GET_ID FUNCTION_BASE
#define GET_VERSION (FUNCTION_BASE+1)
#define GET_KA_STATE (FUNCTION_BASE+2)
#define GET_F_STATE (FUNCTION_BASE+3)
#define GET_SW_STATE (FUNCTION_BASE+4)
#define GET_PRZERWA_STATE (FUNCTION_BASE+5)
#define SET_SA_STATE_HIGH (FUNCTION_BASE+6)
#define SET_SA_STATE_LOW (FUNCTION_BASE+7)
#define SET_ZP_STATE_HIGH (FUNCTION_BASE+8)
#define SET_ZP_STATE_LOW (FUNCTION_BASE+9)
#define GET_LINE_FREQ (FUNCTION_BASE+10)
#define GET_CONTROLS (FUNCTION_BASE+11)
#define GET_AUTO (FUNCTION_BASE+12)
#define SET_DELAYS (FUNCTION_BASE+13)
#define SET_ZP_DELAYS (FUNCTION_BASE+14)
#define STOP_AUTO (FUNCTION_BASE+15)
#define START_AUTO (FUNCTION_BASE+16)

#define SET_DELAY_IP_READ (FUNCTION_BASE+17)
#define SET_DELAY_PILOT_READ (FUNCTION_BASE+18)
#define SET_DELAY_ZP_HIGH_STATE (FUNCTION_BASE+19)
#define SET_DELAY_ZP_LOW_STATE (FUNCTION_BASE+20)
#define SET_DELAY_VALUE_READ (FUNCTION_BASE+21)
#define SET_DELAY_BETWEEN_PILOTS (FUNCTION_BASE+22)
#define SET_DELAY_BETWEEN_IPS (FUNCTION_BASE+23)
#define SET_IP_PM (FUNCTION_BASE+24)

#define GET_DELAY_IP_READ (FUNCTION_BASE+25)
#define GET_DELAY_PILOT_READ (FUNCTION_BASE+26)
#define GET_DELAY_ZP_HIGH_STATE (FUNCTION_BASE+27)
#define GET_DELAY_ZP_LOW_STATE (FUNCTION_BASE+28)
#define GET_DELAY_VALUE_READ (FUNCTION_BASE+29)
#define GET_DELAY_BETWEEN_PILOTS (FUNCTION_BASE+30)
#define GET_DELAY_BETWEEN_IPS (FUNCTION_BASE+31)
#define GET_IP_PM (FUNCTION_BASE+32)

#define SET_PILOT_FREQ_L (FUNCTION_BASE+33)
#define SET_PILOT_FREQ_H (FUNCTION_BASE+34)
#define SET_VALUE_FREQ_L (FUNCTION_BASE+35)
#define SET_VALUE_FREQ_H (FUNCTION_BASE+36)

#define START_CONNECTION (FUNCTION_BASE+37)
#define SEND_ALARM (FUNCTION_BASE+38)
#define CLEAR_ALARM (FUNCTION_BASE+39)

/* Parametry anemometru */
#define PILOT_FREQ_L 1950*18
#define PILOT_FREQ_H 2050*18
#define VALUE_FREQ_L 9471 //7770 Hz
#define VALUE_FREQ_H 5992 //12264 Hz

#define DELAY_AFTER_FRAME_SENDING 0

#define ERROR_TO_LONG_FRAME "Error: Za dluga ramka"
#define FRAME_CHAR_MAX 100
#define FRAME_ENDING '+'
#define FRAME_START ':'
#define SEPARATOR '.'
#define ERROR_RC_TIMEOUT "Error: Timout przy odbiorze znaku"
#define TIMEOUT 1000
#define ERROR_CHAR '!'

typedef enum {idle, pilot, ipa, ipb, ipc, stop} workState;
typedef enum {fregMeasure, alarm} timer0State;